const nodemailer = require('nodemailer');

/**
 * Send complaint letter via email
 * @param {string} to - Recipient email
 * @param {string} subject - Email subject
 * @param {string} body - Email body/letter content
 * @param {Buffer} pdfBuffer - Optional PDF attachment
 */
exports.sendComplaintEmail = async (to, subject, body, pdfBuffer = null) => {
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT) || 587,
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS
    }
  });

  const mailOptions = {
    from: `"LegalMitra AI" <${process.env.SMTP_USER || 'noreply@legalmitra.com'}>`,
    to,
    subject: `Legal Complaint: ${subject}`,
    text: body,
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #6366f1, #8b5cf6); padding: 20px; border-radius: 12px 12px 0 0; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px;">⚖️ LegalMitra AI</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 5px 0 0;">Smart Complaint Platform</p>
        </div>
        <div style="background: #f9fafb; padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
          <h2 style="color: #1f2937; margin-top: 0;">Complaint Letter</h2>
          <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #e5e7eb; white-space: pre-wrap; line-height: 1.6; color: #374151;">
${body}
          </div>
          <p style="color: #9ca3af; font-size: 12px; margin-top: 20px; text-align: center;">
            Generated by LegalMitra AI Platform. This is for informational purposes only.
          </p>
        </div>
      </div>
    `
  };

  if (pdfBuffer) {
    mailOptions.attachments = [{
      filename: 'complaint-letter.pdf',
      content: pdfBuffer,
      contentType: 'application/pdf'
    }];
  }

  try {
    const info = await transporter.sendMail(mailOptions);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('Email sending error:', error.message);
    throw new Error('Failed to send email. Please check SMTP configuration.');
  }
};
