const PDFDocument = require('pdfkit');

/**
 * Generate a PDF complaint letter
 * @param {Object} complaintData - Complaint document from MongoDB
 * @param {string} userName - User's name
 * @param {string} letterContent - Generated letter text
 * @returns {Promise<Buffer>} - PDF buffer
 */
exports.generatePDF = (complaintData, userName, letterContent) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 60, right: 60 }
      });

      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20)
        .font('Helvetica-Bold')
        .text('LEGAL COMPLAINT', { align: 'center' });

      doc.moveDown(0.3);
      doc.fontSize(12)
        .font('Helvetica')
        .fillColor('#6366f1')
        .text('LegalMitra AI Platform', { align: 'center' });

      doc.moveDown(0.5);
      doc.strokeColor('#e2e8f0')
        .lineWidth(1)
        .moveTo(60, doc.y)
        .lineTo(535, doc.y)
        .stroke();

      doc.moveDown(1);

      // Complaint metadata
      doc.fillColor('#374151')
        .fontSize(10)
        .font('Helvetica-Bold')
        .text('Complaint Reference: ', { continued: true })
        .font('Helvetica')
        .text(complaintData._id?.toString() || 'N/A');

      doc.font('Helvetica-Bold')
        .text('Date: ', { continued: true })
        .font('Helvetica')
        .text(new Date().toLocaleDateString('en-IN', {
          day: 'numeric', month: 'long', year: 'numeric'
        }));

      doc.font('Helvetica-Bold')
        .text('Category: ', { continued: true })
        .font('Helvetica')
        .text(complaintData.category || 'General');

      if (complaintData.aiAnalysis?.urgency) {
        doc.font('Helvetica-Bold')
          .text('Urgency: ', { continued: true })
          .font('Helvetica')
          .text(complaintData.aiAnalysis.urgency.toUpperCase());
      }

      doc.moveDown(0.5);
      doc.strokeColor('#e2e8f0')
        .moveTo(60, doc.y)
        .lineTo(535, doc.y)
        .stroke();

      doc.moveDown(1);

      // Letter content
      doc.fillColor('#1f2937')
        .fontSize(11)
        .font('Helvetica')
        .text(letterContent || complaintData.description, {
          align: 'left',
          lineGap: 4
        });

      // Footer
      doc.moveDown(2);
      doc.strokeColor('#e2e8f0')
        .moveTo(60, doc.y)
        .lineTo(535, doc.y)
        .stroke();

      doc.moveDown(0.5);
      doc.fontSize(8)
        .fillColor('#9ca3af')
        .text('This document was generated by LegalMitra AI Platform. It is intended for informational purposes and does not constitute legal advice.', {
          align: 'center'
        });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};
